In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import warnings

warnings.filterwarnings('ignore')

In [2]:
#Lets read temperature file to create the DF
file_temp = "weather_data/temperature.csv"
temp_df = pd.read_csv(file_temp, encoding="ISO-8859-1")
temp_df_city = temp_df[['datetime','Los Angeles','Chicago','Vancouver','Philadelphia','New York']]
temp_df_city_2015 = temp_df_city[temp_df_city['datetime'].str.contains('2015')]

#Remove the NAN. Since we have lot of data we can just drop any values
temp_df_city_2015 = temp_df_city_2015.dropna(how="any")
temp_df_city_2015.head()

,datetime,Los Angeles,Chicago,Vancouver,Philadelphia,New York
19716,2015-01-01 00:00:00,276.988500,266.138500,274.700,268.851000,268.050
19717,2015-01-01 01:00:00,277.518333,266.418333,274.586,267.801667,268.050
19718,2015-01-01 02:00:00,276.311667,266.936667,274.586,267.278333,267.186
19719,2015-01-01 03:00:00,274.348000,266.535500,274.586,267.485500,267.186
19720,2015-01-01 04:00:00,273.393667,267.360333,274.586,266.718667,267.186

In [3]:
temp_df_city_2015[['Year','Month','Ext']] = temp_df_city_2015['datetime'].str.split('-', expand=True)
temp_df_city_2015[['Day','Time']] = temp_df_city_2015['Ext'].str.split(' ', expand=True)
temp_df_city_2015 = temp_df_city_2015.drop(['Ext'], axis=1)
temp_df_city_2015.head()

,datetime,Los Angeles,Chicago,Vancouver,Philadelphia,New York,Year,Month,Day,Time
19716,2015-01-01 00:00:00,276.988500,266.138500,274.700,268.851000,268.050,2015,01,01,00:00:00
19717,2015-01-01 01:00:00,277.518333,266.418333,274.586,267.801667,268.050,2015,01,01,01:00:00
19718,2015-01-01 02:00:00,276.311667,266.936667,274.586,267.278333,267.186,2015,01,01,02:00:00
19719,2015-01-01 03:00:00,274.348000,266.535500,274.586,267.485500,267.186,2015,01,01,03:00:00
19720,2015-01-01 04:00:00,273.393667,267.360333,274.586,266.718667,267.186,2015,01,01,04:00:00

In [4]:
temp_df_city_2015_month = temp_df_city_2015.groupby(['Month'])
temp_df_city_2015_month_avg = temp_df_city_2015_month.mean()
temp_df_city_2015_month_avg

       Los Angeles     Chicago   Vancouver  Philadelphia    New York
Month
01      282.676923  267.862021  279.106892    269.890318  268.970405
02      284.738212  262.712147  280.713602    266.595234  265.911847
03      287.614923  272.986255  280.855311    274.415456  274.168749
04      286.678284  280.327832  281.151683    284.937450  283.328344
05      287.691922  285.515641  287.257669    293.040608  291.882398
06      294.145320  289.400139  291.002764    295.178558  293.496943
07      296.044807  295.252852  293.402823    297.013756  297.396855
08      297.991759  294.711922  292.117849    296.320938  297.193199
09      297.731173  293.296431  287.135419    294.188409  294.737729
10      294.932920  285.780858  285.184121    285.448138  285.803689
11      288.403626  280.492796  277.396015    283.161069  283.263673
12      285.068680  277.446037  277.078608    282.159978  281.808930

In [ ]:
# temp_df_city_2015_date = temp_df_city_2015.groupby(['Month','Day'])
# temp_df_city_2015_date.mean()

In [5]:
#Lets read crime rate for Los Angeles
crime_file = "crime-Los Angeles/LA_CRIME_2010_2017.csv"
crime_LA = pd.read_csv(crime_file, encoding="us-ascii")
crime_LA_2015 = crime_LA[crime_LA['Date Occurred'].str.contains('2015')]
crime_LA_2015

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Weapon Description,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location
200609,809,01/17/2015,01/16/2015,2130,9,Van Nuys,938,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,6200 FULTON AV,NaN,"(34.1814, -118.4263)"
200648,150108522,03/11/2015,03/11/2015,1600,1,Central,143,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0325,...,NaN,IC,Invest Cont,442.0,NaN,NaN,NaN,5TH,BROADWAY,"(34.0481, -118.2507)"
201228,150109432,03/24/2015,03/23/2015,1800,1,Central,185,310,BURGLARY,0344 1602,...,NaN,IC,Invest Cont,310.0,998.0,NaN,NaN,1200 MAPLE AV,NaN,"(34.0388, -118.2574)"
201249,150109804,03/29/2015,03/29/2015,800,1,Central,111,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,800 N HILL ST,NaN,"(34.0628, -118.2395)"
201589,150114304,06/08/2015,06/08/2015,1015,1,Central,144,850,INDECENT EXPOSURE,0529,...,NaN,IC,Invest Cont,850.0,NaN,NaN,NaN,400 S SPRING ST,NaN,"(34.0488, -118.2483)"
201713,150115324,06/24/2015,06/23/2015,2230,1,Central,135,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,200 S MAIN ST,NaN,"(34.051, -118.2445)"
201733,150116252,07/08/2015,07/06/2015,545,1,Central,127,946,OTHER MISCELLANEOUS CRIME,0443,...,VERBAL THREAT,IC,Invest Cont,946.0,NaN,NaN,NaN,JUDGE JOHN AISO,TEMPLE,"(34.0525, -118.2409)"
202598,150116299,07/08/2015,07/08/2015,2355,1,Central,153,888,TRESPASSING,1501,...,NaN,IC,Invest Cont,888.0,NaN,NaN,NaN,500 S SPRING ST,NaN,"(34.0467, -118.252)"
202856,150116489,07/11/2015,07/10/2015,2100,1,Central,192,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,1300 MARGO ST,NaN,"(34.0386, -118.2638)"
205072,150116490,07/11/2015,07/10/2015,2100,1,Central,162,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,700 S HILL ST,NaN,"(34.0462, -118.2585)"
205234,150116494,07/11/2015,07/11/2015,1200,1,Central,142,510,VEHICLE - STOLEN,NaN,...,NaN,AO,Adult Other,510.0,NaN,NaN,NaN,3RD,BROADWAY,"(34.0519, -118.2531)"
205295,150116696,07/14/2015,07/13/2015,1400,1,Central,171,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,900 W OLYMPIC BL,NaN,"(34.0454, -118.2657)"
205673,150116830,07/15/2015,07/15/2015,1600,1,Central,162,350,"THEFT, PERSON",0344,...,NaN,IC,Invest Cont,350.0,NaN,NaN,NaN,700 W 7TH ST,NaN,"(34.048, -118.2577)"
409110,150117314,07/23/2015,07/23/2015,715,1,Central,105,330,BURGLARY FROM VEHICLE,1609 0344,...,NaN,AA,Adult Arrest,330.0,NaN,NaN,NaN,BROADWAY,BISHOPS,"(34.0688, -118.2333)"
490916,150117319,07/23/2015,07/17/2015,1510,1,Central,111,649,DOCUMENT FORGERY / STOLEN FELONY,1402 0800,...,NaN,IC,Invest Cont,649.0,998.0,NaN,NaN,700 N BROADWAY,NaN,"(34.0604, -118.2393)"
571198,150118406,08/08/2015,08/07/2015,2000,1,Central,155,330,BURGLARY FROM VEHICLE,1609 0344,...,NaN,IC,Invest Cont,330.0,NaN,NaN,NaN,6TH,MAPLE,"(34.0439, -118.2479)"
571521,150118407,08/08/2015,08/06/2015,2000,1,Central,121,330,BURGLARY FROM VEHICLE,1609 0344,...,NaN,IC,Invest Cont,330.0,NaN,NaN,NaN,DIAMOND,FIGUEROA,"(34.0589, -118.2527)"
572326,150118562,08/11/2015,08/10/2015,1810,1,Central,153,440,THEFT PLAIN - PETTY ($950 & UNDER),0344,...,NaN,IC,Invest Cont,440.0,NaN,NaN,NaN,500 S BROADWAY,NaN,"(34.0481, -118.2507)"
572606,150119001,08/17/2015,08/16/2015,1530,1,Central,185,310,BURGLARY,0344,...,NaN,AA,Adult Arrest,310.0,NaN,NaN,NaN,1000 S LOS ANGELES ST,NaN,"(34.0396, -118.2558)"
654468,150128751,12/31/2015,12/30/2015,1600,1,Central,111,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,700 N GRAND AV,NaN,"(34.0628, -118.2433)"
981107,150115675,06/29/2015,06/28/2015,1730,1,Central,185,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,HILL,12TH,"(34.0387, -118.2611)"
981166,150307045,02/21/2015,02/19/2015,1500,3,Southwest,356,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,WESTERN,35TH,"(34.0247, -118.3089)"
981305,150411088,06/17/2015,06/17/2015,400,4,Hollenbeck,424,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,VALLEY,SOTO,"(34.0646, -118.197)"
981349,150125362,11/14/2015,11/13/2015,1300,1,Central,133,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,3RD,SPRING,"(34.051, -118.248)"
981410,150125678,11/18/2015,11/15/2015,200,1,Central,152,351,PURSE SNATCHING,0344 0448,...,NaN,IC,Invest Cont,351.0,NaN,NaN,NaN,7TH,HOPE,"(34.048, -118.2577)"
981516,150113111,05/20/2015,05/19/2015,1830,1,Central,182,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,FLOWER,OLYMPIC,"(34.0444, -118.2628)"
981535,150104713,01/13/2015,01/13/2015,110,1,Central,153,350,"THEFT, PERSON",0346 1238,...,NaN,IC,Invest Cont,350.0,NaN,NaN,NaN,5TH,SPRING,"(34.0478, -118.2502)"
981593,150506835,03/05/2015,03/04/2015,2200,5,Harbor,557,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,1ST,CABRILLO,"(33.7433, -118.2945)"
981823,150125680,11/18/2015,11/18/2015,2300,1,Central,157,350,"THEFT, PERSON",0344,...,NaN,IC,Invest Cont,350.0,NaN,NaN,NaN,5TH,SAN PEDRO,"(34.0442, -118.2439)"
981964,150508750,04/18/2015,04/17/2015,2120,5,Harbor,529,510,VEHICLE - STOLEN,NaN,...,NaN,AA,Adult Arrest,510.0,NaN,NaN,NaN,ANAHEIM,FRIES,"(33.7753, -118.2456)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1577264,171917047,08/24/2017,02/01/2015,1530,19,Mission,1984,354,THEFT OF IDENTITY,1822 1258,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,8800 WILLIS AV,NaN,"(34.23, -118.4553)"
1577584,172016211,08/26/2017,09/18/2015,800,20,Olympic,2064,354,THEFT OF IDENTITY,0100 0935,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,1200 S ARDMORE AV,NaN,"(34.0491, -118.3021)"
1577703,172110508,05/11/2017,04/01/2015,1,21,Topanga,2118,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,0400 0500 0503 0556,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,812.0,860.0,NaN,NaN,ROSCOE,WINNETKA,"(34.2202, -118.571)"
1577826,172115870,08/26/2017,09/29/2015,1550,21,Topanga,2158,310,BURGLARY,0344 1606,...,NaN,IC,Invest Cont,310.0,NaN,NaN,NaN,6400 DE SOTO AV,NaN,"(34.1865, -118.5886)"
1577971,151708618,04/08/2015,04/07/2015,2200,17,Devonshire,1785,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,8800 ETIWANDA AV,NaN,"(34.2308, -118.5324)"
1577995,150313844,06/06/2015,06/01/2015,1900,3,Southwest,399,235,CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT,1257 0407 0553,...,SCALDING LIQUID,AO,Adult Other,235.0,NaN,NaN,NaN,400 W 41ST PL,NaN,"(34.0083, -118.2815)"
1577996,150323315,10/27/2015,10/25/2015,550,3,Southwest,341,815,SEXUAL PENTRATION WITH A FOREIGN OBJECT,0913 1309 0522,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,815.0,NaN,NaN,NaN,3600 KALSMAN DR,NaN,"(34.0218, -118.3746)"
1577997,150401124,09/07/2015,09/07/2015,945,4,Hollenbeck,428,626,INTIMATE PARTNER - SIMPLE ASSAULT,2000 1243 1813 0416 0329,...,NaN,AO,Adult Other,626.0,NaN,NaN,NaN,2900 PHELPS AV,NaN,"(34.0802, -118.1769)"
1577998,150413399,08/17/2015,08/17/2015,700,4,Hollenbeck,468,626,INTIMATE PARTNER - SIMPLE ASSAULT,2000 1243 0400 0444 0421,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,Adult Arrest,626.0,NaN,NaN,NaN,3000 E 4TH ST,NaN,"(34.0388, -118.1987)"
1577999,150417939,12/11/2015,12/11/2015,135,4,Hollenbeck,412,626,INTIMATE PARTNER - SIMPLE ASSAULT,2000 1814 0400 2002 0416,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,626.0,NaN,NaN,NaN,2200 PASADENA AV,NaN,"(34.0752, -118.2188)"
1578000,151110892,05/20/2015,05/19/2015,2240,11,Northeast,1148,330,BURGLARY FROM VEHICLE,0344 1307 1402,...,NaN,IC,Invest Cont,330.0,998.0,NaN,NaN,FIGUEROA ST,AVENUE 50,"(34.105, -118.2022)"
1578001,151119351,11/05/2015,11/02/2015,2000,11,Northeast,1118,520,VEHICLE - ATTEMPT STOLEN,1402 1501 0344,...,NaN,IC,Invest Cont,520.0,998.0,NaN,NaN,5600 IRVINGTON PL,NaN,"(34.1155, -118.1977)"
1578002,151500786,06/27/2015,06/23/2015,1830,15,N Hollywood,1539,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1402,...,NaN,AO,Adult Other,740.0,998.0,NaN,NaN,5900 RIVERTON AV,NaN,"(34.1776, -118.3659)"
1578028,160406592,02/29/2016,11/21/2015,1,4,Hollenbeck,455,626,INTIMATE PARTNER - SIMPLE ASSAULT,2000 0416 1814 2002,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,626.0,NaN,NaN,NaN,2100 E CESAR E CHAVEZ AV,NaN,"(34.0512, -118.2093)"
1578081,161119207,11/14/2016,10/01/2015,1300,11,Northeast,1128,956,"LETTERS, LEWD",NaN,...,NaN,AO,Adult Other,956.0,NaN,NaN,NaN,6300 JACQUELINE ST,NaN,"(34.1261, -118.1803)"
1578102,161616924,11/29/2016,05/21/2015,800,16,Foothill,1653,662,"BUNCO, GRAND THEFT",0701 1202,...,NaN,IC,Invest Cont,662.0,NaN,NaN,NaN,12900 KAGEL CANYON ST,NaN,"(34.2559, -118.4143)"
1578561,170215867,08/20/2017,04/01/2015,2000,2,Rampart,231,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,2000 1813 0416 2002,...,BLUNT INSTRUMENT,IC,Invest Cont,236.0,NaN,NaN,NaN,200 ROBINSON ST,NaN,"(34.0742, -118.2831)"
1579115,170320634,09/05/2017,05/01/2015,1,3,Southwest,377,354,THEFT OF IDENTITY,1822 0100,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,1300 W MARTIN LUTHER KING JR BL,NaN,"(34.0145, -118.298)"
1579167,170320721,09/06/2017,11/25/2015,1930,3,Southwest,314,354,THEFT OF IDENTITY,0100 0928 1822,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,3700 W 27TH ST,NaN,"(34.0312, -118.3251)"
1579487,170415198,09/07/2017,02/01/2015,1200,4,Hollenbeck,404,821,SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO...,0519 1259 1824,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,812.0,821.0,NaN,NaN,5500 VIA MARISOL,NaN,"(34.1045, -118.185)"
1579727,170515683,09/05/2017,01/01/2015,100,5,Harbor,528,813,CHILD ANNOYING (17YRS & UNDER),0400 1258,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,813.0,NaN,NaN,NaN,1000 SANFORD AV,NaN,"(33.7835, -118.2505)"
1579985,170619074,09/06/2017,08/27/2015,200,6,Hollywood,622,946,OTHER MISCELLANEOUS CRIME,1501,...,NaN,IC,Invest Cont,946.0,NaN,NaN,NaN,7900 ZEUS DR,NaN,"(34.1133, -118.3681)"
1580270,170715359,09/09/2017,03/01/2015,1,7,Wilshire,767,354,THEFT OF IDENTITY,0928 1822,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,1400 S NORTON AV,NaN,"(34.0459, -118.3243)"
1580912,171015504,09/05/2017,05/06/2015,800,10,West Valley,1015,815,SEXUAL PENTRATION WITH A FOREIGN OBJECT,0556 0515,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,812.0,815.0,NaN,NaN,7500 NEWCASTLE AV,NaN,"(34.2066, -118.5251)"
1580936,171015553,09/07/2017,07/01/2015,1500,10,West Valley,1037,956,"LETTERS, LEWD",NaN,...,NaN,IC,Invest Cont,956.0,NaN,NaN,NaN,17100 VANOWEN ST,NaN,"(34.1939, -118.5055)"
1581383,171221918,09/02/2016,09/02/2015,1036,12,77th Street,1213,624,BATTERY - SIMPLE ASSAULT,1309 0416 0446,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,624.0,NaN,NaN,NaN,1600 W 52ND ST,NaN,"(33.9951, -118.3046)"
1581502,171222074,09/05/2017,06/01/2015,1200,12,77th Street,1213,354,THEFT OF IDENTITY,0100 0929 0926 1822,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,1600 W 52ND ST,NaN,"(33.9951, -118.3046)"
1582824,171716583,08/30/2017,06/15/2015,1200,17,Devonshire,1756,354,THEFT OF IDENTITY,1822,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,17800 LASSEN ST,NaN,"(34.254, -118.5128)"
1583299,171818180,09/05/2017,07/22/2015,100,18,Southeast,1826,946,OTHER MISCELLANEOUS CRIME,1501,...,NaN,IC,Invest Cont,946.0,NaN,NaN,NaN,1500 E 99TH ST,NaN,"(33.947, -118.248)"
1583345,171818304,09/06/2017,11/01/2015,1100,18,Southeast,1836,354,THEFT OF IDENTITY,0377 0928 1822,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,1400 E 108TH ST,NaN,"(33.9378, -118.2499)"

In [6]:
crime_LA_2015[['Month','Day','Year']] = crime_LA_2015['Date Occurred'].str.split('/', expand=True)
crime_LA_2015.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,Month,Day,Year
200609,809,01/17/2015,01/16/2015,2130,9,Van Nuys,938,510,VEHICLE - STOLEN,NaN,...,510.0,NaN,NaN,NaN,6200 FULTON AV,NaN,"(34.1814, -118.4263)",01,16,2015
200648,150108522,03/11/2015,03/11/2015,1600,1,Central,143,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0325,...,442.0,NaN,NaN,NaN,5TH,BROADWAY,"(34.0481, -118.2507)",03,11,2015
201228,150109432,03/24/2015,03/23/2015,1800,1,Central,185,310,BURGLARY,0344 1602,...,310.0,998.0,NaN,NaN,1200 MAPLE AV,NaN,"(34.0388, -118.2574)",03,23,2015
201249,150109804,03/29/2015,03/29/2015,800,1,Central,111,510,VEHICLE - STOLEN,NaN,...,510.0,NaN,NaN,NaN,800 N HILL ST,NaN,"(34.0628, -118.2395)",03,29,2015
201589,150114304,06/08/2015,06/08/2015,1015,1,Central,144,850,INDECENT EXPOSURE,0529,...,850.0,NaN,NaN,NaN,400 S SPRING ST,NaN,"(34.0488, -118.2483)",06,08,2015

In [7]:
crime_LA_2015_month = crime_LA_2015.groupby('Month')
crime_LA_2015_month_count_df = crime_LA_2015_month.count()
crime_LA_2015_month_count_df

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,Day,Year
Month,,,,,,,,,,,,,,,,,,,,,
01,17981,17981,17981,17981,17981,17981,17981,17981,17977,16073,...,17981,17981,1144,33,2,17981,2847,17981,17981,17981
02,15930,15930,15930,15930,15930,15930,15930,15930,15928,14287,...,15930,15930,1035,37,2,15930,2586,15930,15930,15930
03,17907,17907,17907,17907,17907,17907,17907,17907,17900,16149,...,17907,17907,1264,38,2,17907,2895,17907,17907,17907
04,16869,16869,16869,16869,16869,16869,16869,16869,16868,15275,...,16869,16869,1138,45,3,16869,2727,16869,16869,16869
05,17839,17839,17839,17839,17839,17839,17839,17839,17837,16083,...,17839,17839,1237,30,0,17839,2904,17839,17839,17839
06,17423,17423,17423,17423,17423,17423,17423,17423,17423,15767,...,17423,17423,1203,33,0,17423,2910,17423,17423,17423
07,18553,18553,18553,18553,18553,18553,18553,18553,18550,16679,...,18553,18553,1257,29,0,18553,3060,18553,18553,18553
08,18877,18877,18877,18877,18877,18877,18877,18877,18873,16873,...,18877,18876,1259,31,1,18877,3164,18877,18877,18877
09,18152,18152,18152,18152,18152,18152,18152,18152,18151,16275,...,18152,18152,1233,31,0,18152,3078,18152,18152,18152
10,19065,19065,19065,19065,19065,19065,19065,19065,19060,16913,...,19065,19064,1218,31,0,19065,3313,19065,19065,19065
11,17240,17240,17240,17240,17240,17240,17240,17240,17235,15271,...,17240,17240,1087,30,0,17240,2649,17240,17240,17240
12,18074,18074,18074,18074,18074,18074,18074,18074,18061,15946,...,18074,18074,1139,33,0,18074,2669,18074,18074,18074

In [8]:
temp_df_city_2015_month_avg['Crime Los Angeles'] = crime_LA_2015_month_count_df['Date Occurred']
temp_df_city_2015_month_avg

,Los Angeles,Chicago,Vancouver,Philadelphia,New York,Crime Los Angeles
Month,,,,,,
01,282.676923,267.862021,279.106892,269.890318,268.970405,17981
02,284.738212,262.712147,280.713602,266.595234,265.911847,15930
03,287.614923,272.986255,280.855311,274.415456,274.168749,17907
04,286.678284,280.327832,281.151683,284.937450,283.328344,16869
05,287.691922,285.515641,287.257669,293.040608,291.882398,17839
06,294.145320,289.400139,291.002764,295.178558,293.496943,17423
07,296.044807,295.252852,293.402823,297.013756,297.396855,18553
08,297.991759,294.711922,292.117849,296.320938,297.193199,18877
09,297.731173,293.296431,287.135419,294.188409,294.737729,18152
10,294.932920,285.780858,285.184121,285.448138,285.803689,19065
11,288.403626,280.492796,277.396015,283.161069,283.263673,17240
12,285.068680,277.446037,277.078608,282.159978,281.808930,18074

In [10]:
#Lets read crime rate for Chicago
crime_file = "crime-Chicago/CHI_CRIME_2012_2017.csv"
crime_CHI = pd.read_csv(crime_file, encoding="us-ascii")

crime_CHI_2015 = crime_CHI[crime_CHI['Date'].str.contains('2015')]
crime_CHI_2015

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
154,36509,10514462,HZ256372,01/01/2015 12:00:00 AM,073XX S EXCHANGE AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,NURSING HOME/RETIREMENT HOME,False,...,7.0,43.0,02,NaN,NaN,2015,05/10/2016 03:56:50 PM,NaN,NaN,NaN
157,37451,10515175,HZ257172,11/24/2015 05:30:00 PM,033XX W ADAMS ST,0820,THEFT,$500 AND UNDER,RESIDENCE,False,...,28.0,27.0,06,NaN,NaN,2015,05/10/2016 03:56:50 PM,NaN,NaN,NaN
190,46637,10077106,HY266148,05/19/2015 01:12:00 AM,009XX W BELMONT AVE,0560,ASSAULT,SIMPLE,APARTMENT,True,...,44.0,6.0,08A,1169640.0,1921442.0,2015,05/11/2016 03:48:18 PM,41.939943,-87.651925,"(41.939943264, -87.651924995)"
191,46745,10301916,HY469211,01/01/2015 12:00:00 AM,062XX W BARRY AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,True,...,36.0,19.0,02,1134262.0,1919947.0,2015,05/11/2016 03:48:18 PM,41.936539,-87.781987,"(41.936538876, -87.781987083)"
744,207345,10160687,HY313819,06/24/2015 06:00:00 AM,052XX N MARMORA AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,RESIDENCE,True,...,45.0,11.0,18,1135867.0,1934466.0,2015,05/12/2016 03:48:29 PM,41.976352,-87.775741,"(41.976351974, -87.775741229)"
745,207432,10181647,HY215976,04/09/2015 04:30:51 PM,061XX S CHAMPLAIN AVE,2024,NARCOTICS,POSS: HEROIN(WHITE),RESIDENCE,True,...,20.0,42.0,18,1181623.0,1864501.0,2015,05/12/2016 03:48:29 PM,41.783424,-87.609648,"(41.783424215, -87.609648327)"
746,207605,10192026,HY360910,07/29/2015 04:21:21 PM,029XX W FLOURNOY ST,2027,NARCOTICS,POSS: CRACK,APARTMENT,True,...,2.0,27.0,18,1156974.0,1896894.0,2015,05/12/2016 03:48:29 PM,41.872848,-87.699144,"(41.872848316, -87.69914356)"
747,207671,10203133,HY381916,08/14/2015 10:55:00 AM,054XX W WALTON ST,1821,NARCOTICS,MANU/DEL:CANNABIS 10GM OR LESS,VEHICLE NON-COMMERCIAL,True,...,37.0,25.0,18,1139924.0,1905802.0,2015,05/12/2016 03:48:29 PM,41.897622,-87.761525,"(41.897621617, -87.761524853)"
748,207803,10211492,HY257237,05/12/2015 11:54:19 AM,066XX S WASHTENAW AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,RESIDENCE,True,...,15.0,66.0,18,1159517.0,1860604.0,2015,05/12/2016 03:48:29 PM,41.773212,-87.690803,"(41.773212262, -87.690803401)"
750,208172,10211589,HY340025,07/14/2015 06:00:00 AM,033XX W FILLMORE ST,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,POLICE FACILITY/VEH PARKING LOT,True,...,24.0,29.0,18,1154228.0,1895173.0,2015,05/12/2016 03:48:29 PM,41.868181,-87.709271,"(41.868180939, -87.709271389)"
751,208606,10211597,HY334821,07/10/2015 06:00:00 AM,006XX W OHARE ST,2093,NARCOTICS,FOUND SUSPECT NARCOTICS,GOVERNMENT BUILDING/PROPERTY,True,...,41.0,76.0,18,1100088.0,1926079.0,2015,05/12/2016 03:48:29 PM,41.953900,-87.907473,"(41.953900467, -87.907472601)"
753,208950,10211611,HY333584,07/09/2015 06:00:00 AM,033XX W FILLMORE ST,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,POLICE FACILITY/VEH PARKING LOT,True,...,24.0,29.0,18,1154228.0,1895173.0,2015,05/12/2016 03:48:29 PM,41.868181,-87.709271,"(41.868180939, -87.709271389)"
754,209491,10211617,HY333517,07/09/2015 06:00:00 AM,033XX W FILLMORE ST,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,POLICE FACILITY/VEH PARKING LOT,True,...,24.0,29.0,18,1154228.0,1895173.0,2015,05/12/2016 03:48:29 PM,41.868181,-87.709271,"(41.868180939, -87.709271389)"
755,210010,10211621,HY369125,08/04/2015 05:24:00 PM,075XX S STONY ISLAND AVE,2017,NARCOTICS,MANU/DELIVER:CRACK,VEHICLE NON-COMMERCIAL,True,...,5.0,43.0,18,1188123.0,1855151.0,2015,05/12/2016 03:48:29 PM,41.757614,-87.586115,"(41.757614433, -87.586115266)"
757,210309,10211623,HY331028,07/07/2015 06:00:00 AM,033XX W FILLMORE ST,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,POLICE FACILITY/VEH PARKING LOT,True,...,24.0,29.0,18,1154228.0,1895173.0,2015,05/12/2016 03:48:29 PM,41.868181,-87.709271,"(41.868180939, -87.709271389)"
758,210353,10211630,HY323307,07/01/2015 06:00:00 AM,033XX W FILLMORE ST,2031,NARCOTICS,POSS: METHAMPHETAMINES,POLICE FACILITY/VEH PARKING LOT,True,...,24.0,29.0,18,1154228.0,1895173.0,2015,05/12/2016 03:48:29 PM,41.868181,-87.709271,"(41.868180939, -87.709271389)"
759,210920,10212757,HY369072,08/04/2015 04:51:00 PM,007XX S KEDVALE AVE,2024,NARCOTICS,POSS: HEROIN(WHITE),APARTMENT,True,...,24.0,26.0,18,1148838.0,1896308.0,2015,05/12/2016 03:48:29 PM,41.871401,-87.729030,"(41.871401333, -87.729029971)"
760,210964,10212800,HY368655,08/04/2015 11:53:00 AM,005XX N LAWLER AVE,2017,NARCOTICS,MANU/DELIVER:CRACK,VEHICLE NON-COMMERCIAL,True,...,28.0,25.0,18,1142599.0,1903190.0,2015,05/12/2016 03:48:29 PM,41.890405,-87.751765,"(41.890404638, -87.751764782)"
761,211440,10213138,HY371827,08/06/2015 04:58:08 PM,013XX S HOMAN AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,APARTMENT,True,...,24.0,29.0,18,1153916.0,1893520.0,2015,05/12/2016 03:48:29 PM,41.863651,-87.710461,"(41.863651143, -87.71046084)"
762,211591,10213157,HY371446,08/06/2015 12:18:43 PM,014XX W 66TH ST,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,APARTMENT,True,...,17.0,67.0,18,1167978.0,1860982.0,2015,05/12/2016 03:48:29 PM,41.774072,-87.659776,"(41.774071891, -87.659776488)"
763,212008,10213250,HY371306,08/06/2015 11:42:00 AM,050XX W DIVISION ST,1821,NARCOTICS,MANU/DEL:CANNABIS 10GM OR LESS,SIDEWALK,True,...,37.0,25.0,18,1142681.0,1907524.0,2015,05/12/2016 03:48:29 PM,41.902296,-87.751356,"(41.902296112, -87.75135567)"
764,212592,10214240,HY370160,08/05/2015 02:00:00 PM,013XX N HUDSON AVE,2014,NARCOTICS,MANU/DELIVER: HEROIN (WHITE),SIDEWALK,True,...,27.0,8.0,18,1173067.0,1909543.0,2015,05/12/2016 03:48:29 PM,41.907216,-87.639684,"(41.907216451, -87.639683562)"
765,213157,10214258,HY370494,08/05/2015 05:05:00 PM,015XX E 76TH ST,2017,NARCOTICS,MANU/DELIVER:CRACK,VEHICLE NON-COMMERCIAL,True,...,5.0,43.0,18,1187947.0,1854903.0,2015,05/12/2016 03:48:29 PM,41.756938,-87.586768,"(41.756938091, -87.586768161)"
767,213465,10214280,HY370501,08/05/2015 05:22:00 PM,0000X E 87TH ST,1822,NARCOTICS,MANU/DEL:CANNABIS OVER 10 GMS,PARKING LOT/GARAGE(NON.RESID.),True,...,6.0,44.0,18,1178069.0,1847315.0,2015,05/12/2016 03:48:29 PM,41.736345,-87.623199,"(41.736345248, -87.623198545)"
769,213970,10214340,HY373225,08/07/2015 05:53:42 PM,012XX S FAIRFIELD AVE,2024,NARCOTICS,POSS: HEROIN(WHITE),APARTMENT,True,...,28.0,29.0,18,1158231.0,1894123.0,2015,05/12/2016 03:48:29 PM,41.865219,-87.694604,"(41.865218836, -87.694604216)"
770,214014,10217851,HY381066,08/13/2015 01:59:54 PM,013XX N LOCKWOOD AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,APARTMENT,True,...,37.0,25.0,18,1140785.0,1908250.0,2015,05/12/2016 03:48:29 PM,41.904323,-87.758302,"(41.904323426, -87.758302186)"
771,214298,10217898,HY381838,08/14/2015 07:52:55 AM,035XX N PULASKI RD,2022,NARCOTICS,POSS: COCAINE,RESIDENCE,True,...,30.0,16.0,18,1149094.0,1923450.0,2015,05/12/2016 03:48:29 PM,41.945877,-87.727386,"(41.945876706, -87.727386135)"
772,214385,10218176,HY381348,08/13/2015 07:33:00 PM,015XX E 76TH PL,2027,NARCOTICS,POSS: CRACK,RESIDENCE,True,...,5.0,43.0,18,1187741.0,1854562.0,2015,05/12/2016 03:48:29 PM,41.756007,-87.587534,"(41.756007259, -87.587533939)"
773,214667,10218922,HY234127,04/24/2015 11:50:00 AM,071XX S ASHLAND AVE,2024,NARCOTICS,POSS: HEROIN(WHITE),STREET,True,...,17.0,67.0,18,1166924.0,1857157.0,2015,05/12/2016 03:48:29 PM,41.763598,-87.663749,"(41.763598176, -87.663749413)"
774,214776,10218939,HY223482,04/15/2015 06:55:10 PM,089XX S CHAPPEL AVE,2027,NARCOTICS,POSS: CRACK,RESIDENCE,True,...,8.0,48.0,18,1191398.0,1846199.0,2015,05/12/2016 03:48:29 PM,41.732971,-87.574402,"(41.732970661, -87.574402377)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1451347,6230802,10815006,JA114229,11/29/2015 12:00:00 PM,008XX N LA SALLE DR,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,RESIDENCE,False,...,42.0,8.0,26,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1451408,6230863,10818684,JA119085,01/28/2015 05:20:00 PM,034XX W HARRISON ST,0810,THEFT,OVER $500,RESIDENCE,False,...,24.0,27.0,06,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1451414,6230869,10818833,JA119151,04/21/2015 09:00:00 AM,109XX S EGGLESTON AVE,1156,DECEPTIVE PRACTICE,ATTEMPT - FINANCIAL IDENTITY THEFT,RESIDENCE,False,...,34.0,49.0,11,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1451426,6230881,10818936,JA119217,06/08/2015 12:00:00 AM,086XX S PRAIRIE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,6.0,44.0,11,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1451442,6230897,10819077,JA119577,11/21/2015 09:00:00 AM,065XX W SCHORSCH ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,36.0,17.0,11,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1451448,6230903,10819106,JA119533,11/17/2015 05:20:00 PM,064XX N RICHMOND ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,...,50.0,2.0,26,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1451449,6230904,10819107,JA119250,08/15/2015 12:00:00 PM,055XX N MAPLEWOOD AVE,0810,THEFT,OVER $500,APARTMENT,False,...,40.0,4.0,06,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1451469,6230925,10819336,JA119812,03/01/2015 10:00:00 AM,061XX W SEMINOLE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,45.0,10.0,11,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1451474,6230930,10819503,JA120061,08/26/2015 02:30:00 PM,003XX W OHIO ST,0460,BATTERY,SIMPLE,OTHER,False,...,42.0,8.0,08B,NaN,NaN,2015,01/18/2017 03:50:44 PM,NaN,NaN,NaN
1452117,6231574,10819939,JA120298,09/05/2015 12:01:00 AM,033XX W 37TH PL,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,OTHER,False,...,12.0,58.0,17,NaN,NaN,2015,01/19/2017 03:56:04 PM,NaN,NaN,NaN
1452124,6231581,10820023,JA120323,12/19/2015 12:00:00 PM,0000X N STATE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,DEPARTMENT STORE,False,...,42.0,32.0,11,NaN,NaN,2015,01/19/2017 03:56:04 PM,NaN,NaN,NaN
1452148,6231605,10820228,JA120744,02/15/2015 10:00:00 PM,068XX W THORNDALE AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,...,41.0,10.0,02,NaN,NaN,2015,01/19/2017 03:56:04 PM,NaN,NaN,NaN
1452168,6231626,10820218,JA120588,09/01/2015 08:00:00 AM,031XX W 54TH ST,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,RESIDENCE,False,...,14.0,63.0,17,NaN,NaN,2015,01/23/2017 03:49:47 PM,NaN,NaN,NaN
1452231,6231689,9923486,HY112577,01/12/2015 05:06:00 PM,062XX S RACINE AVE,0454,BATTERY,AGG PO HANDS NO/MIN INJURY,CTA BUS,True,...,16.0,67.0,08B,1169393.0,1863312.0,2015,01/20/2017 03:48:51 PM,41.780435,-87.654522,"(41.780435167, -87.654521948)"
1452850,6232308,10817466,JA117786,01/01/2015 08:00:00 AM,026XX S KEELER AVE,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,...,22.0,30.0,20,NaN,NaN,2015,01/20/2017 03:50:54 PM,NaN,NaN,NaN
1453714,6233178,10822151,JA122886,02/25/2015 12:01:00 AM,064XX S ABERDEEN ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,16.0,68.0,11,NaN,NaN,2015,01/21/2017 03:48:36 PM,NaN,NaN,NaN
1453740,6233205,10822452,JA123087,01/30/2015 10:00:00 AM,026XX W CORTEZ ST,1156,DECEPTIVE PRACTICE,ATTEMPT - FINANCIAL IDENTITY THEFT,RESIDENCE,False,...,1.0,24.0,11,NaN,NaN,2015,01/21/2017 03:48:36 PM,NaN,NaN,NaN
1453767,6233232,10822722,JA123209,12/01/2015 10:00:00 AM,043XX S ASHLAND AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,SMALL RETAIL STORE,False,...,11.0,61.0,11,NaN,NaN,2015,01/21/2017 03:48:36 PM,NaN,NaN,NaN
1455050,6234515,10821749,JA121798,12/08/2015 04:46:00 PM,008XX N MICHIGAN AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,SMALL RETAIL STORE,False,...,42.0,8.0,11,NaN,NaN,2015,01/23/2017 03:52:03 PM,NaN,NaN,NaN
1455064,6234529,10824124,JA125445,10/01/2015 12:00:00 AM,048XX S CHICAGO BEACH DR,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,...,4.0,39.0,20,NaN,NaN,2015,01/23/2017 03:52:03 PM,NaN,NaN,NaN
1455161,6234626,10027721,HY217048,04/10/2015 03:24:00 PM,013XX N HAMLIN AVE,0560,ASSAULT,SIMPLE,ALLEY,True,...,30.0,23.0,08A,1150797.0,1908688.0,2015,01/24/2017 03:52:49 PM,41.905335,-87.721514,"(41.905335285, -87.721513604)"
1455162,6234627,10047679,HY237134,04/26/2015 09:10:00 PM,020XX N LOREL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,...,37.0,19.0,08B,1140385.0,1913288.0,2015,01/24/2017 03:52:49 PM,41.918156,-87.759648,"(41.918155616, -87.759647736)"
1455163,6234628,10448086,HZ186848,12/25/2015 04:00:00 AM,132XX S EXCHANGE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,True,...,10.0,55.0,14,1197774.0,1817667.0,2015,01/24/2017 03:52:49 PM,41.654519,-87.551993,"(41.654519371, -87.551992754)"
1455183,6234648,9938531,HY126195,01/23/2015 06:25:00 PM,078XX W FOREST PRESERVE AVE,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,STREET,False,...,36.0,17.0,17,1123048.0,1923361.0,2015,01/24/2017 03:52:49 PM,41.946098,-87.823126,"(41.946097835, -87.823126111)"
1455184,6234649,9999861,HY189254,03/17/2015 11:54:00 AM,013XX N SPRINGFIELD AVE,051A,ASSAULT,AGGRAVATED: HANDGUN,RESIDENCE PORCH/HALLWAY,True,...,30.0,23.0,04A,1150131.0,1908814.0,2015,01/24/2017 03:52:49 PM,41.905694,-87.723957,"(41.90569405, -87.723956771)"
1455797,6235262,10825209,JA126392,04/26/2015 12:00:00 PM,056XX N PARKSIDE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,45.0,11.0,11,NaN,NaN,2015,01/24/2017 03:55:11 PM,NaN,NaN,NaN
1455822,6235287,10825575,JA126902,09/01/2015 12:00:00 AM,085XX W BERWYN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,41.0,76.0,11,NaN,NaN,2015,01/24/2017 03:55:11 PM,NaN,NaN,NaN
1455858,6235323,10825882,JA127213,10/23/2015 12:00:00 AM,036XX S HONORE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,...,11.0,59.0,11,NaN,NaN,2015,01/24/2017 03:55:11 PM,NaN,NaN,NaN
1455884,6235349,21864,HY264682,05/18/2015 12:54:00 AM,078XX S SOUTH SHORE DR,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,...,7.0,43.0,01A,NaN,NaN,2015,01/24/2017 03:55:11 PM,NaN,NaN,NaN
1456615,6236082,10827202,JA128229,04/15/2015 08:35:00 AM,028XX W LYNDALE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,...,35.0,22.0,11,NaN,NaN,2015,01/25/2017 03:54:12 PM,NaN,NaN,NaN

In [16]:
crime_CHI_2015[['Month','Day','Ext']] = crime_CHI_2015['Date'].str.split('/', expand=True)
crime_CHI_2015[['Year','Time']] = crime_CHI_2015['Ext'].str.split(' ', 1, expand=True)
crime_CHI_2015 = crime_CHI_2015.drop(['Ext'], axis=1)

crime_CHI_2015.head()

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Month,Day,Time
154,36509,10514462,HZ256372,01/01/2015 12:00:00 AM,073XX S EXCHANGE AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,NURSING HOME/RETIREMENT HOME,False,...,NaN,NaN,2015,05/10/2016 03:56:50 PM,NaN,NaN,NaN,01,01,12:00:00 AM
157,37451,10515175,HZ257172,11/24/2015 05:30:00 PM,033XX W ADAMS ST,0820,THEFT,$500 AND UNDER,RESIDENCE,False,...,NaN,NaN,2015,05/10/2016 03:56:50 PM,NaN,NaN,NaN,11,24,05:30:00 PM
190,46637,10077106,HY266148,05/19/2015 01:12:00 AM,009XX W BELMONT AVE,0560,ASSAULT,SIMPLE,APARTMENT,True,...,1169640.0,1921442.0,2015,05/11/2016 03:48:18 PM,41.939943,-87.651925,"(41.939943264, -87.651924995)",05,19,01:12:00 AM
191,46745,10301916,HY469211,01/01/2015 12:00:00 AM,062XX W BARRY AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,True,...,1134262.0,1919947.0,2015,05/11/2016 03:48:18 PM,41.936539,-87.781987,"(41.936538876, -87.781987083)",01,01,12:00:00 AM
744,207345,10160687,HY313819,06/24/2015 06:00:00 AM,052XX N MARMORA AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,RESIDENCE,True,...,1135867.0,1934466.0,2015,05/12/2016 03:48:29 PM,41.976352,-87.775741,"(41.976351974, -87.775741229)",06,24,06:00:00 AM

In [17]:
crime_CHI_2015_month = crime_CHI_2015.groupby('Month')
crime_CHI_2015_month_count_df = crime_CHI_2015_month.count()
crime_CHI_2015_month_count_df

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Day,Time
Month,,,,,,,,,,,,,,,,,,,,,
01,20656,20656,20656,20656,20656,20656,20656,20656,20639,20656,...,20656,20309,20309,20656,20656,20309,20309,20309,20656,20656
02,16287,16287,16287,16287,16287,16287,16287,16287,16267,16287,...,16287,16079,16079,16287,16287,16079,16079,16079,16287,16287
03,21560,21560,21560,21560,21560,21560,21560,21560,21530,21560,...,21560,21271,21271,21560,21560,21271,21271,21271,21560,21560
04,21610,21610,21610,21610,21610,21610,21610,21610,21594,21610,...,21610,21467,21467,21610,21610,21467,21467,21467,21610,21610
05,23570,23570,23570,23570,23570,23570,23570,23570,23560,23570,...,23570,23355,23355,23570,23570,23355,23355,23355,23570,23570
06,23059,23059,23059,23059,23059,23059,23059,23059,23044,23059,...,23059,22930,22930,23059,23059,22930,22930,22930,23059,23059
07,24101,24101,24101,24101,24101,24101,24101,24101,24086,24101,...,24101,23915,23915,24101,24101,23915,23915,23915,24101,24101
08,24685,24685,24685,24685,24685,24685,24685,24685,24667,24685,...,24685,24472,24472,24685,24685,24472,24472,24472,24685,24685
09,22996,22996,22996,22996,22996,22996,22996,22996,22979,22996,...,22996,22716,22716,22996,22996,22716,22716,22716,22996,22996
10,22979,22979,22979,22979,22979,22979,22979,22979,22963,22979,...,22979,22639,22639,22979,22979,22639,22639,22639,22979,22979
11,20486,20486,20486,20486,20486,20486,20486,20486,20453,20486,...,20486,20156,20156,20486,20486,20156,20156,20156,20486,20486
12,21006,21006,21006,21006,21006,21006,21006,21006,20956,21006,...,21006,20486,20486,21006,21006,20486,20486,20486,21006,21006

In [18]:
temp_df_city_2015_month_avg['Crime Chicago'] = crime_CHI_2015_month_count_df['Date']
temp_df_city_2015_month_avg

,Los Angeles,Chicago,Vancouver,Philadelphia,New York,Crime Los Angeles,Crime Chicago
Month,,,,,,,
01,282.676923,267.862021,279.106892,269.890318,268.970405,17981,20656
02,284.738212,262.712147,280.713602,266.595234,265.911847,15930,16287
03,287.614923,272.986255,280.855311,274.415456,274.168749,17907,21560
04,286.678284,280.327832,281.151683,284.937450,283.328344,16869,21610
05,287.691922,285.515641,287.257669,293.040608,291.882398,17839,23570
06,294.145320,289.400139,291.002764,295.178558,293.496943,17423,23059
07,296.044807,295.252852,293.402823,297.013756,297.396855,18553,24101
08,297.991759,294.711922,292.117849,296.320938,297.193199,18877,24685
09,297.731173,293.296431,287.135419,294.188409,294.737729,18152,22996
10,294.932920,285.780858,285.184121,285.448138,285.803689,19065,22979
11,288.403626,280.492796,277.396015,283.161069,283.263673,17240,20486
12,285.068680,277.446037,277.078608,282.159978,281.808930,18074,21006